dagster-user-deployments:
  enabled: true
  deployments:
    - name: "k8s-ours"
      image:
        repository: "hub.docker.com/leobocci/dagster_test"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/example_pipe.py"
      port: 8081