dagster-user-deployments:
  enabled: true
  deployments:
    - name: "k8s-ours"
      image:
        repository: "leobocci/dagster_test"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/app/__init__.py"
      port: 8081